Image descriptions for 7.3
ULeth-Math-CS/APEXCalculusPTX pull request #11
Opened 2023-10-21 23:42 UTC by supervladimir

2023-10-27 13:18 UTC, sean-fitzpatrick requested changes
Great work! Minor changes only.

2023-10-27 13:18 UTC, sean-fitzpatrick commented on ptx/sec_shell_method.ptx
> +              The region above <m>y=0.5</m> forms a shape which looks a perfectly symmetrical mountiain or hill, whose peak is the point <m>(0,1,0)</m>.
- looks like (missing word)
- typo: mountain

2023-10-27 13:18 UTC, sean-fitzpatrick commented on ptx/sec_shell_method.ptx
> +              The cylinder has a height <m> h </m>, radius <m> r </m> and is pictured lying on it's circular base.
should be "its" and not "it's"

2023-10-27 13:18 UTC, sean-fitzpatrick commented on ptx/sec_shell_method.ptx
> +              Both the circular base, and the top of the cylinder are shaded, while the curved surface is unshaded, but contains a "cut here" instruction.
there are xml tags for quotes (so they get handled correctly in LaTeX, etc: use `<q>cut here</q>`

2023-10-27 13:18 UTC, sean-fitzpatrick commented on ptx/sec_shell_method.ptx
> +              The cylindrical shell has a height <m> h </m>, radius <m> r </m> which spans from the cut out center to the edge of the shell, and the shell has thickness <m> \dx </m> and is pictured l
same comments: "its", and the quotes.

2023-10-27 13:18 UTC, sean-fitzpatrick commented on ptx/sec_shell_method.ptx
> +              This vertical line is labelled <m>h(x)</m>, and will give the us the height of the cylindrical shell.
For consistency with the rest of the book, we should use the American spelling 'labeled'.
(I don't like it, but it is what it is... Some day I'll make a Canadian edition.)

2023-10-27 13:18 UTC, sean-fitzpatrick commented on ptx/sec_shell_method.ptx
> +                  This vertical line is labelled <m>h(x)</m>, and will give the us the height of the cylindrical shells.
labeled again

2023-10-28 22:59 UTC, supervladimir commented
The errors should now be fixed.

2023-10-30 15:34 UTC, sean-fitzpatrick approved these changes

2023-10-30 15:34 UTC, merged